apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu-sleeper
  name: ubuntu-sleeper
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - "4800"
    image: ubuntu
    securityContext:
       runAsUser: 0
       capabilities:
          add: ["SYS_TIME","NET_ADMIN"]
    name: ubuntu-sleeper
